### PR TITLE
Return response, not just (parsed) body of it

### PR DESCRIPTION
**Pull request by michaelsauter**
This allows to inspect headers etc in the future.

### CODE REVIEW

**Comment by mungler** [comment]
@michaelsauter This is nice, but I think we should include updates to the documentation explaining the change, with a migration guide to the new behaviour (i.e. having to explicitly call `.result` on the response object).

**Comment by michaelsauter** [comment]
@mungler Updated the documentation in c5691a4.

**Comment by michaelsauter** [comment]
ping @mungler

**Comment by mungler** [comment]
Looks good :)

**Pull request merged**
