### PR TITLE
Export segment

### PR DESCRIPTION
**Pull request by michaelsauter**

### CODE REVIEW

**Comment by michaelsauter** [comment]
@mungler Sorry for all the nagging, could we get this in as well? As far as I can tell, this should be the last thing we need for now :)

**Comment by mungler** [comment]
Merged and new gem build 0.3.1 released. Thanks! 👍

**Comment by mungler** [comment]
@michaelsauter :)

**Comment by michaelsauter** [comment]
@mungler Thanks a lot.

**Comment by michaelsauter** [comment]
@mungler Tried to update to 0.3.1 today but https://rubygems.org/gems/emarsys doesn't list it yet. Did you forget to push it maybe?

**Pull request merged**
