### PR TITLE
Enable response summary api with optional params

### PR DESCRIPTION
**Pull request by headshota**
Optional params: launch_id, start_date, end_date

### CODE REVIEW

**Comment by headshota** [comment]
@michaelsauter FYI

**Comment by headshota** [comment]
@mungler could you please have a look? would be great if we can merge this.

**Comment by mungler** [comment]
@headshota looks good. Could you update specs to cover this usage?

**Comment by mungler** [comment]
@headshota bump

**Comment by headshota** [comment]
@mungler apologies for the late response, updated the spec, hope it's sufficient

**Comment by headshota** [comment]
@mungler apologies for the late response, updated the specs, hope it is sufficient.

**Pull request merged**
