### PR TITLE
Implement responses endpoints

### PR DESCRIPTION
**Pull request by michaelsauter**
Oh man, new week, new change ... sorry ;)

### CODE REVIEW

**Comment by michaelsauter** [comment]
@mungler ping :)

**Comment by michaelsauter** [comment]
@mungler @carpodaster Could you please have a look? That would be great. Also #40 would be important to have merged ...

**Comment by mungler** [comment]
@michaelsauter apologies - holidays and business trip got in the way...

**Comment by michaelsauter** [comment]
@mungler No worries :)

**Pull request merged**
