### PR TITLE
Documentation for country mapping utility

### PR DESCRIPTION
**Pull request by mungler**
Added some documentation to the README for the country code mapper.

### CODE REVIEW

**Comment by mungler** [comment]
@carpodaster thoughts?

**Comment by carpodaster** [comment]
@mugler looks great. 🎊 and 👍 for not leaving the docs behind!

With so many merged PRs, would you like to be added as a collaborator? We at ABSOLVENTA don't use Emarsys anymore and maintenance of this gem is very low on our priority list.

**Comment by mungler** [comment]
@carpodaster sure - i'm partway through an integration project with Emarsys, so there may well be further tweaks and fixes I need to make.  Thanks!

**Comment by mungler** [comment]
@carpodaster thanks for the add.  One thing - would it be worth bumping the version and pushing a new gem up to rubygems?

**Comment by carpodaster** [comment]
@mungler I've just released v0.2.0

**Comment by mungler** [comment]
@carpodaster great news 👍 will switch our project to using that, barring any more updates I end up needing to make :)

**Pull request merged**
