### PR TITLE
WIP: Multiple configs

### PR DESCRIPTION
**Pull request by michaelsauter**
Work in progress, do not merge yet.

### CODE REVIEW

**Comment by michaelsauter** [comment]
Alright, I changed all methods to keyword arguments and added multiple account config.

Some unclear bits:

1. First, I realized that some methods don't cover all API params but simply receive a `params` hash which is passed through. Since I don't want to change all those methods, the easiest would be to use `**params` (as you suggested @carpodaster) in this case. However, it's not a good approach for other use cases. Imagine we had `Contact.create(key_id:, key_value:, account: nil, **params)`. Ruby does not like it very much if you want to use integer keys for that, e.g.: `Emarsys::Contact.create(key_id: 3, key_value: "john.doe@example.com", 1 => 'John', 2 => "Doe")`. Because of that, I opted for an explicit `params: {}` kwarg in this case.

2. Some methods take an ID which is the ID of a resource and that ID is also part of the URL. In that case, I opted for a normal arguments, e.g. `def destroy(id, account: nil)`.

3. Related to (2), `Event.trigger` and `Event.trigger_multiple` take an `event_id` according to the documentation. For consistency, I chose `Event.trigger(id, key_id:, external_id:, data: {}, account: nil)` and `Event.trigger_multiple(id, key_id:, contacts:, account: nil)` now.

4. Some methods previously took arguments with different names then the API, e.g. `base64_encoded_file` instead of `file`. I chose to use the API param name instead.

Let me know what you think.

If everything looks good, I'll adapt the documentation and changelog.

**Comment by michaelsauter** [comment]
ping @mungler

**Comment by mungler** [comment]
@michaelsauter apologies for the delay, I was on vacation.  Yes, this looks really good. Please update the docs accordingly and we can merge.

**Comment by michaelsauter** [comment]
@mungler No worries. I've added documentation. Now that it is getting longer and longer I chose to move the changelog to its own file, hope that is fine with you.

**Comment by michaelsauter** [comment]
@mungler Sorry to push this again, but would it be possible to merge this? We need to move forward with this internally now, so a new version would be awesome.

**Comment by mungler** [comment]
@michaelsauter v0.3.0 released on rubygems.org

@carpodaster @dansch FYI

**Comment by michaelsauter** [comment]
Thanks!

**Pull request merged**
